<?xml version="1.0" encoding="UTF-8"?>
<ns1:model xmlns:e="aurora.service.exception" xmlns:o="aurora.database.local.oracle" xmlns:ns1="http://www.aurora-framework.org/schema/bm" xmlns:f="aurora.database.features" alias="fc" baseTable="sys_user">
    <ns1:fields>
        <ns1:field name="user_id" databaseType="BIGINT" datatype="java.lang.Long" isAutoGeneratedKey="true"/>
        <ns1:field name="user_name" databaseType="VARCHAR" datatype="java.lang.String" prompt="SYS_USER.ACCOUNT"/>
        <ns1:field name="encrypted_foundation_password" databaseType="VARCHAR" datatype="java.lang.String" insertExpression="upper(md5(${@user_password}))"/>
        <ns1:field name="encrypted_user_password" databaseType="VARCHAR" datatype="java.lang.String" insertExpression="upper(md5(${@user_password_re}))"/>
        <ns1:field name="last_logon_date" databaseType="DATE" datatype="java.sql.Date" forInsert="true" forUpdate="true"/>
        <ns1:field name="description" databaseType="VARCHAR" datatype="java.lang.String" prompt="SYS_USER.DESCRIPTION"/>
    </ns1:fields>
    <ns1:primary-key>
        <ns1:pk-field name="user_id"/>
    </ns1:primary-key>
    <ns1:query-fields>
        <ns1:query-field field="user_id" queryOperator="="/>
        <ns1:query-field field="user_name" queryOperator="like"/>
    </ns1:query-fields>
    <ns1:features>
    </ns1:features>
    <e:exception-descriptor-config>
        <e:exception-descriptor exception="java.sql.SQLException" handleClass="aurora.database.SQLExceptionDescriptor">
            <e:error-message code="1" message="SYS_USER.ACCOUNT_DISTICNT"/>
        </e:exception-descriptor>
    </e:exception-descriptor-config>
</ns1:model>
